services:
  api:
    build: 
      context: ./server
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./server:/usr/src/api
    ports:
      - 3001:3001
  web:
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
